### ISSUE TITLE
Hi, how do you calculate the ECE score and Brier score in paper.

### ISSUE THREAD

**Issue by eyuansu62** [NoviScl/GPT3-Reliability#1]
The difference between my calculated score and the paper is more than one order of magnitude. So I am curious about it.

**Comment by NoviScl** [comment]
Hi! 
For ECE, see: https://github.com/NoviScl/calibrateQA/blob/main/calibrator.py#L137
For Brier, see: https://github.com/NoviScl/calibrateQA/blob/main/calibrator.py#L155 
And by default, we split predictions into ten equal-interval buckets. 

Also note that we multiplied all raw numbers by 100 as a default for easier reading of the results (e.g., 45 means 0.45).

**Comment by eyuansu62** [comment]
Thanks for your reply! Could you please give more hint here?
Does per_bucket_score mean accuracy of each bucket, and per_bucket_confidence mean average confidence of each bucket?

And in get_bucket_scores_and_confidence(self.test_top_scores, self.test_top_probs), is test_top_scores here a list containing [0,1] standing for true or false, and test_top_probs a list containing the probs of positive class?

**Comment by NoviScl** [comment]
Yes, and yes. (For QA, scores means EM, prob means the probability of the answer string). 
For more details on how to get the probability of the answer strings, see our prompting GPT-3 paper for the case of GPT-3, and see my other calibration paper (https://arxiv.org/abs/2205.12507) for the case of DPR-BERT.

**Comment by eyuansu62** [comment]
Thanks a lot!!!!! BTW, great job! :)
