### ISSUE TITLE
Normalized language model probability

### ISSUE THREAD

**Issue by lisaalaz** [NoviScl/GPT3-Reliability#3]
Hi! Thank you for your very interesting experiments in Prompting GPT-3 to Be Realiable.

I just wanted to ask, when for uncertainty calibration you use the normalized LM probability, is it already normalized (i.e. raised to 1/N) when you obtain it from the API? I did not see the normalization step in the code.

Many thanks!

**Comment by NoviScl** [comment]
Yes, it is normalized: https://github.com/NoviScl/GPT3-Reliability/blob/main/cot.py#L301 (`np.mean(top_probs)` is taking the mean of log_probs for all output tokens).
